12.3 search
thinknetica-django-lab-04/griefrelayer pull request #102
Opened 2021-09-05 19:08 UTC by griefrelayer

Closes #97

2021-09-06 09:26 UTC, morgangt requested changes

2021-09-06 09:26 UTC, morgangt commented on bulletin_board/main/consumer.py
> +        d = datetime.now()
почему d ?

2021-09-06 09:26 UTC, morgangt commented on bulletin_board/main/consumer.py
> +                                                   "time": d.isoformat(), "text": search_result}})
почему не сразу 
```
"time": datetime.now().isoformat()

```

2021-09-06 09:26 UTC, morgangt commented on bulletin_board/main/consumer.py
> +                 + str(ad.price) + "</div></div>"
заменить на f-string и вынести в отдельную функцию

2021-09-06 09:26 UTC, morgangt commented on bulletin_board/main/consumer.py
> +                      + f'<div class="d-flex flex-column">{value}</div></div>'
вынести в отдельный метод

2021-09-06 09:26 UTC, morgangt commented on bulletin_board/main/templatetags/extra_tags.py
> +    try:
надо добавить docstring

2021-09-06 09:26 UTC, morgangt commented on bulletin_board/main/templatetags/extra_tags.py
> +        res = 0
почему 0 а не ошибка

2021-09-07 06:16 UTC, griefrelayer commented on bulletin_board/main/templatetags/extra_tags.py
> +        res = 0
Честно не помню, как я получил ошибку TypeError, пока уберу это

2021-09-07 06:24 UTC, griefrelayer commented on bulletin_board/main/consumer.py
> +                      + f'<div class="d-flex flex-column">{value}</div></div>'
сделано

2021-09-07 06:24 UTC, griefrelayer commented on bulletin_board/main/consumer.py
> +                                                   "time": d.isoformat(), "text": search_result}})
поправил

2021-09-10 05:39 UTC, morgangt approved these changes

2021-09-10 06:08 UTC, merged