5.2 allauth
thinknetica-django-lab-04/griefrelayer pull request #50
Opened 2021-08-11 06:23 UTC by griefrelayer

Closes #43

2021-08-11 07:31 UTC, morgangt requested changes

2021-08-11 07:31 UTC, morgangt commented on bulletin_board/bulletin_board/settings.py
> +            'secret': 'nFzjSX6hH0QRdPOsr7_2aeNf',
Эти секреты и токены не должно быть в git, их надо передавать как конфигурацию в проект, потому что разрабатываемое ПО может быть использовано не только вами и не только для одного проекта, вам надо перегенировать token потом что все что было закомиченно в git останеться в git и потом злоумышленники смогут найти по истории коммитов в git, token и использовать его от вашего имени

2021-08-11 08:05 UTC, griefrelayer commented on bulletin_board/bulletin_board/settings.py
> +            'secret': 'nFzjSX6hH0QRdPOsr7_2aeNf',
Я подумал, что после этого проекта удалю эти данные из панели google, а так, возможно, проще будет проверить работу. Ок, принято. Убрал из кода

2021-08-16 11:30 UTC, morgangt approved these changes

2021-08-16 12:41 UTC, merged